# Generated by Django 4.0.2 on 2022-02-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_proc', models.CharField(max_length=10)),
                ('link_proc', models.CharField(max_length=500)),
                ('partner', models.CharField(max_length=512)),
                ('summ_proc', models.IntegerField()),
                ('count_order', models.IntegerField()),
                ('subj_proc', models.CharField(max_length=512)),
                ('actual_for_me', models.IntegerField(choices=[(0, 'не актуально'), (1, 'актуально')])),
            ],
        ),
    ]
