# Generated by Django 4.0.2 on 2022-07-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='hash',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
