# Generated by Django 4.0.2 on 2022-07-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0002_procedures_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='interesting',
            field=models.SmallIntegerField(default=0),
        ),
    ]
