# Generated by Django 4.0.2 on 2022-04-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0002_laws_marketplaces_order_orgs_portalgroups_stages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='proc_number',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
