# Generated by Django 4.0.2 on 2022-07-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0003_procedures_interesting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedures',
            name='interesting',
        ),
        migrations.CreateModel(
            name='Interesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.SmallIntegerField()),
                ('inter', models.ManyToManyField(to='indexpage.Procedures')),
            ],
        ),
    ]
