# Generated by Django 4.0.2 on 2022-04-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0004_tradeplaces_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='link',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
