# Generated by Django 4.0.2 on 2022-04-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0005_procedures_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='procedures',
            name='deal_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
