# Generated by Django 4.0.2 on 2022-07-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0005_alter_interesting_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interesting',
            old_name='inter',
            new_name='procedure',
        ),
    ]
