# Generated by Django 4.0.6 on 2022-08-09 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indexpage', '0006_rename_inter_interesting_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
