# Generated by Django 4.0.2 on 2022-04-10 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0006_region_procedures_deal_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='indexpage.region'),
        ),
    ]
