# Generated by Django 4.0.2 on 2022-04-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0007_procedures_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_proc', models.CharField(max_length=128)),
                ('link_proc', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=128)),
                ('type_proc', models.CharField(max_length=128)),
                ('partner', models.CharField(max_length=512)),
                ('pertner_inn', models.CharField(max_length=512)),
                ('summ_proc', models.CharField(max_length=20)),
                ('count_order', models.CharField(max_length=5)),
                ('region', models.CharField(max_length=128)),
                ('law_proc', models.CharField(max_length=128)),
                ('subj_proc', models.CharField(max_length=512)),
                ('complete', models.IntegerField(default=0)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('proc_comment', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'raw_table',
                'managed': True,
            },
        ),
    ]
