# Generated by Django 4.0.6 on 2022-08-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0008_userorgs_userorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_num', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('day_to_shipping', models.SmallIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexpage.userorders')),
            ],
        ),
    ]
