# Generated by Django 4.0.2 on 2022-04-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0008_rawdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawdata',
            old_name='pertner_inn',
            new_name='partner_inn',
        ),
    ]
