# Generated by Django 4.0.6 on 2022-08-14 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0009_usercontracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorders',
            name='my_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexpage.userorgs'),
        ),
    ]
