# Generated by Django 4.0.6 on 2022-08-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0010_alter_userorders_my_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeplaces',
            name='full_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tradeplaces',
            name='link',
            field=models.CharField(blank=True, max_length=521, null=True),
        ),
    ]
