# Generated by Django 4.0.6 on 2022-08-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0011_alter_tradeplaces_full_name_alter_tradeplaces_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='personal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
