# Generated by Django 4.0.6 on 2022-08-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0012_procedures_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='summ_proc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
